server:
  port: ${SERVICE_SERVER_PORT}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  packagesToScan: com.runapp.storyprogressservice

eureka:
  client:
    enabled: false

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      database: admin
#  datasource:
#    url: jdbc:postgres:///${DATABASE_NAME}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    driver-class-name:
#    hikari:
#      data-source-properties:
#        socketFactory: com.google.cloud.sql.postgres.SocketFactory
#        cloudSqlInstance: ${SQL_INSTANCE_NAME}
#        enableIamAuth: true
#        sslmode: disable
#      maximum-pool-size: 6
#      minimum-idle: 5
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#    hibernate:
#      ddl-auto: create-drop
  application:
    name: story-progress-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 6MB
  cloud:
    service-registry:
      auto-registration:
        enabled: false
